### ISSUE TITLE
Updates for React 15 or React-Router 2.4?

### ISSUE THREAD

**Issue by jmargolisvt** [RachBLondon/polling-app-with-socketio#13]
I got through adding ReactDOM ok, but the changes in React-Router 2.4 make it tough to get through Part 3 of this tutorial.  Are there any plans to update the tutorial or add update notes somewhere?

**Comment by RachBLondon** [comment]
Hi,  I did not write this tutorial, I was just working through it and put it, so sorry I can't answer your question. Maybe keep checking Lynda to see.
